dev:
  domain: "vbat@127.0.0.1"
  deploy_to: "/home/vbat/git/test_blazing_dev"
  repository: "git@github.com:vichaos/test_blazing.git"
  branch: "master"
  post_setup_script: "bin/post_setup.sh"
  rake_env:
    RAILS_ENV: 'development'

